apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kubeconv 
spec:
  replicas: 20
  selector: 
    matchLabels:
      app: kubeconv  
  template:
    metadata: 
      labels:
        app: kubeconv  
    spec:
      containers: 
      - name: kubeconv
        image: cout01/kube-news:v2 
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: kube-conv  
spec:
  selector: 
    app: kubeconv 
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort         